build = "cargo build --target-dir target/"
test = "cargo test"
clippy-fix = "cargo clippy --fix --bin jake"
clippy = "cargo clippy"
format = "cargo fmt"
format-check = "cargo fmt --check"
version-bump = "python3 scripts/version_bump.py"
npm-publish = "bash scripts/login_and_publish_to_npm.sh"
