say-hello = { command = "echo 'hello'" }
say-hello-back = { command = "echo 'hello back'" }
say-bye = { command = "echo 'bye'", depends_on = ["say-hello", "say-hello-back"] }
list = { command = "ls" }
